/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#191c1e",
        "danger": "#DC2626",
        "warning": "#EAB308",
        "background": "#f8f9fb",
        "surface-container-lowest": "#ffffff",
        "grad-honor": "linear-gradient(135deg, #3B82F6, #4F46E5)",
        "inverse-primary": "#b4c5ff",
        "grad-travel": "linear-gradient(135deg, #10B981, #0D9488)",
        "tertiary-container": "#a65900",
        "on-primary-fixed-variant": "#003ea8",
        "on-primary-fixed": "#00174b",
        "inverse-surface": "#2e3132",
        "grad-food": "linear-gradient(135deg, #F97316, #D97706)",
        "surface-container-low": "#f3f4f6",
        "on-tertiary-container": "#ffede1",
        "on-tertiary-fixed-variant": "#6e3900",
        "secondary-fixed-dim": "#68dba9",
        "on-primary": "#ffffff",
        "surface-dim": "#d9dadc",
        "secondary": "#006c4a",
        "surface-bright": "#f8f9fb",
        "primary": "#004ac6",
        "on-primary-container": "#eeefff",
        "tertiary-fixed-dim": "#ffb77d",
        "on-error-container": "#93000a",
        "surface-container": "#edeef0",
        "inverse-on-surface": "#f0f1f3",
        "primary-fixed-dim": "#b4c5ff",
        "grad-realization": "linear-gradient(135deg, #F97316, #DC2626)",
        "text-high": "#111827",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "grad-maintenance": "linear-gradient(135deg, #F43F5E, #DB2777)",
        "outline": "#737686",
        "tertiary-fixed": "#ffdcc3",
        "on-secondary-fixed": "#002114",
        "grad-support": "linear-gradient(135deg, #A855F7, #7C3AED)",
        "surface-tint": "#0053db",
        "surface": "#f8f9fb",
        "surface-variant": "#e1e2e4",
        "on-surface-variant": "#434655",
        "on-surface": "#191c1e",
        "tertiary": "#824500",
        "grad-admin": "linear-gradient(135deg, #4B5563, #334155)",
        "surface-container-highest": "#e1e2e4",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#005137",
        "secondary-container": "#82f5c1",
        "outline-variant": "#c3c6d7",
        "secondary-fixed": "#85f8c4",
        "text-low": "#6B7280",
        "primary-fixed": "#dbe1ff",
        "on-tertiary-fixed": "#2f1500",
        "grad-workshop": "linear-gradient(135deg, #06B6D4, #0284C7)",
        "on-secondary-container": "#00714e",
        "surface-container-high": "#e7e8ea",
        "primary-container": "#2563eb",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        sm: "8px",
        xl: "32px",
        xs: "4px",
        md: "16px",
        base: "4px",
        "margin-page": "24px",
        gutter: "16px",
        lg: "24px",
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-xs": ["Inter", "sans-serif"],
        "headline-sm": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-xs": ["12px", { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-sm": ["20px", { lineHeight: "1.4", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
      },
      animation: {
        "fade-in": "fadeIn 0.5s ease-out",
        "slide-in": "slideIn 0.3s ease-out",
        "slide-in-left": "slideInLeft 0.35s cubic-bezier(0.16, 1, 0.3, 1)",
        "slide-in-right": "slideInRight 0.35s cubic-bezier(0.16, 1, 0.3, 1)",
        "toast-in": "toastIn 0.4s cubic-bezier(0.21, 1.02, 0.73, 1)",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideIn: {
          "0%": { transform: "translateX(-10px)", opacity: "0" },
          "100%": { transform: "translateX(0)", opacity: "1" },
        },
        slideInLeft: {
          "0%": { transform: "translateX(-10px)", opacity: "0" },
          "100%": { transform: "translateX(0)", opacity: "1" },
        },
        slideInRight: {
          "0%": { transform: "translateX(100%)", opacity: "0" },
          "100%": { transform: "translateX(0)", opacity: "1" },
        },
        toastIn: {
          "0%": { transform: "translateX(100%)", opacity: "0" },
          "100%": { transform: "translateX(0)", opacity: "1" },
        },
      },
    },
  },
  plugins: [],
}
